/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    usbd_cdc_if.c
  * @brief   USB CDC (Virtual COM Port) interface for UltraLogic R1
  * @version 1.0
  *
  * @company PE Info
  * @author  Umit Kayacik
  * @date    2026
  *
  * @details
  *   Implements the USB CDC class callbacks, most importantly the
  *   CDC_Receive_FS() function that parses ASCII commands sent by the
  *   PC application (sw/main.py) and dispatches them to the appropriate
  *   UltraLogic driver functions.
  *
  *   Supported commands (PC → FW, terminated by \r\n):
  *
  *     SET:FREQ:<hz>                  (output frequency, 1-400 Hz)
  *     SET:SWF:<hz>                   (switching frequency, 1000-20000 Hz)
  *     SET:MOD:<0-1155>               (modulation index, per-mille)
  *
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2026 PE Info.  All rights reserved.
  *
  * This software contains portions generated by STM32CubeMX.
  * STMicroelectronics licence terms apply to the auto-generated sections.
  *
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "usbd_cdc_if.h"

/* USER CODE BEGIN INCLUDE */
#include "ul_drivers.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
/* USER CODE END INCLUDE */

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
/* Private macro -------------------------------------------------------------*/

/* USER CODE BEGIN PV */
/* Private variables ---------------------------------------------------------*/

/* USER CODE END PV */

/** @addtogroup STM32_USB_OTG_DEVICE_LIBRARY
  * @brief Usb device library.
  * @{
  */

/** @addtogroup USBD_CDC_IF
  * @{
  */

/** @defgroup USBD_CDC_IF_Private_TypesDefinitions USBD_CDC_IF_Private_TypesDefinitions
  * @brief Private types.
  * @{
  */

/* USER CODE BEGIN PRIVATE_TYPES */

/* USER CODE END PRIVATE_TYPES */

/**
  * @}
  */

/** @defgroup USBD_CDC_IF_Private_Defines USBD_CDC_IF_Private_Defines
  * @brief Private defines.
  * @{
  */

/* USER CODE BEGIN PRIVATE_DEFINES */
/* USER CODE END PRIVATE_DEFINES */

/**
  * @}
  */

/** @defgroup USBD_CDC_IF_Private_Macros USBD_CDC_IF_Private_Macros
  * @brief Private macros.
  * @{
  */

/* USER CODE BEGIN PRIVATE_MACRO */

/* USER CODE END PRIVATE_MACRO */

/**
  * @}
  */

/** @defgroup USBD_CDC_IF_Private_Variables USBD_CDC_IF_Private_Variables
  * @brief Private variables.
  * @{
  */
/* Create buffer for reception and transmission           */
/* It's up to user to redefine and/or remove those define */
/** Received data over USB are stored in this buffer      */
uint8_t UserRxBufferFS[APP_RX_DATA_SIZE];

/** Data to send over USB CDC are stored in this buffer   */
uint8_t UserTxBufferFS[APP_TX_DATA_SIZE];

/* USER CODE BEGIN PRIVATE_VARIABLES */
static uint8_t LineCoding[7] = {
    0x00, 0xC2, 0x01, 0x00,  /* 115200 bps (little-endian) */
    0x00,                     /* 1 stop bit  */
    0x00,                     /* no parity   */
    0x08                      /* 8 data bits */
};
/* USER CODE END PRIVATE_VARIABLES */

/**
  * @}
  */

/** @defgroup USBD_CDC_IF_Exported_Variables USBD_CDC_IF_Exported_Variables
  * @brief Public variables.
  * @{
  */

extern USBD_HandleTypeDef hUsbDeviceFS;

/* USER CODE BEGIN EXPORTED_VARIABLES */

/* USER CODE END EXPORTED_VARIABLES */

/**
  * @}
  */

/** @defgroup USBD_CDC_IF_Private_FunctionPrototypes USBD_CDC_IF_Private_FunctionPrototypes
  * @brief Private functions declaration.
  * @{
  */

static int8_t CDC_Init_FS(void);
static int8_t CDC_DeInit_FS(void);
static int8_t CDC_Control_FS(uint8_t cmd, uint8_t* pbuf, uint16_t length);
static int8_t CDC_Receive_FS(uint8_t* pbuf, uint32_t *Len);
static int8_t CDC_TransmitCplt_FS(uint8_t *pbuf, uint32_t *Len, uint8_t epnum);

/* USER CODE BEGIN PRIVATE_FUNCTIONS_DECLARATION */

/* USER CODE END PRIVATE_FUNCTIONS_DECLARATION */

/**
  * @}
  */

USBD_CDC_ItfTypeDef USBD_Interface_fops_FS =
{
  CDC_Init_FS,
  CDC_DeInit_FS,
  CDC_Control_FS,
  CDC_Receive_FS,
  CDC_TransmitCplt_FS
};

/* Private functions ---------------------------------------------------------*/
/**
  * @brief  Initializes the CDC media low layer over the FS USB IP
  * @retval USBD_OK if all operations are OK else USBD_FAIL
  */
static int8_t CDC_Init_FS(void)
{
  /* USER CODE BEGIN 3 */
  /* Set Application Buffers */
  USBD_CDC_SetTxBuffer(&hUsbDeviceFS, UserTxBufferFS, 0);
  USBD_CDC_SetRxBuffer(&hUsbDeviceFS, UserRxBufferFS);
  return (USBD_OK);
  /* USER CODE END 3 */
}

/**
  * @brief  DeInitializes the CDC media low layer
  * @retval USBD_OK if all operations are OK else USBD_FAIL
  */
static int8_t CDC_DeInit_FS(void)
{
  /* USER CODE BEGIN 4 */
  return (USBD_OK);
  /* USER CODE END 4 */
}

/**
  * @brief  Manage the CDC class requests
  * @param  cmd: Command code
  * @param  pbuf: Buffer containing command data (request parameters)
  * @param  length: Number of data to be sent (in bytes)
  * @retval Result of the operation: USBD_OK if all operations are OK else USBD_FAIL
  */
static int8_t CDC_Control_FS(uint8_t cmd, uint8_t* pbuf, uint16_t length)
{
  /* USER CODE BEGIN 5 */
  switch(cmd)
  {
    case CDC_SEND_ENCAPSULATED_COMMAND:

    break;

    case CDC_GET_ENCAPSULATED_RESPONSE:

    break;

    case CDC_SET_COMM_FEATURE:

    break;

    case CDC_GET_COMM_FEATURE:

    break;

    case CDC_CLEAR_COMM_FEATURE:

    break;

  /*******************************************************************************/
  /* Line Coding Structure                                                       */
  /*-----------------------------------------------------------------------------*/
  /* Offset | Field       | Size | Value  | Description                          */
  /* 0      | dwDTERate   |   4  | Number |Data terminal rate, in bits per second*/
  /* 4      | bCharFormat |   1  | Number | Stop bits                            */
  /*                                        0 - 1 Stop bit                       */
  /*                                        1 - 1.5 Stop bits                    */
  /*                                        2 - 2 Stop bits                      */
  /* 5      | bParityType |  1   | Number | Parity                               */
  /*                                        0 - None                             */
  /*                                        1 - Odd                              */
  /*                                        2 - Even                             */
  /*                                        3 - Mark                             */
  /*                                        4 - Space                            */
  /* 6      | bDataBits  |   1   | Number Data bits (5, 6, 7, 8 or 16).          */
  /*******************************************************************************/
    case CDC_SET_LINE_CODING:
      memcpy(LineCoding, pbuf, sizeof(LineCoding));
    break;

    case CDC_GET_LINE_CODING:
      memcpy(pbuf, LineCoding, sizeof(LineCoding));
    break;

    case CDC_SET_CONTROL_LINE_STATE:

    break;

    case CDC_SEND_BREAK:

    break;

  default:
    break;
  }

  return (USBD_OK);
  /* USER CODE END 5 */
}

/**
  * @brief  Data received over USB OUT endpoint are sent over CDC interface
  *         through this function.
  *
  *         @note
  *         This function will issue a NAK packet on any OUT packet received on
  *         USB endpoint until exiting this function. If you exit this function
  *         before transfer is complete on CDC interface (ie. using DMA controller)
  *         it will result in receiving more data while previous ones are still
  *         not sent.
  *
  * @param  Buf: Buffer of data to be received
  * @param  Len: Number of data received (in bytes)
  * @retval Result of the operation: USBD_OK if all operations are OK else USBD_FAIL
  */
static int8_t CDC_Receive_FS(uint8_t* Buf, uint32_t *Len)
{
  /* USER CODE BEGIN 6 */
  if (*Len >= APP_RX_DATA_SIZE)
      *Len = APP_RX_DATA_SIZE - 1;
  Buf[*Len] = '\0';
  char *line = (char *)Buf;

  while (*line == '\r' || *line == '\n' || *line == ' ') line++;
  size_t len = strlen(line);
  if (len > 0) {
      char *end = line + len - 1;
      while (end > line && (*end == '\r' || *end == '\n' || *end == ' ')) *end-- = '\0';
  }
  if (*line == '\0') {
      USBD_CDC_SetRxBuffer(&hUsbDeviceFS, &Buf[0]);
      USBD_CDC_ReceivePacket(&hUsbDeviceFS);
      return (USBD_OK);
  }

  if (strncmp(line, "SET:FREQ:", 9) == 0) {
      uint32_t v = (uint32_t)strtoul(line + 9, NULL, 10);
      UL_SVPWM_SetOutFreq(v);
  } else if (strncmp(line, "SET:SWF:", 8) == 0) {
      uint32_t v = (uint32_t)strtoul(line + 8, NULL, 10);
      UL_SVPWM_SetSwFreq(v);
  } else if (strncmp(line, "SET:MOD:", 8) == 0) {
      uint32_t v = (uint32_t)strtoul(line + 8, NULL, 10);
      UL_SVPWM_SetModIndex(v);
  } else if (strncmp(line, "SET:SVPWM:", 10) == 0) {
      uint32_t v = (uint32_t)strtoul(line + 10, NULL, 10);
      if (v) {
          UL_SVPWM_Enable();
      } else {
          UL_SVPWM_Disable();
      }
  } else if (strncmp(line, "SET:TEST:", 9) == 0) {
      uint32_t v = (uint32_t)strtoul(line + 9, NULL, 10);
      UL_SVPWM_SetTestMode((uint8_t)(v != 0));
      UL_SVPWM_Init();
  } else if (strncmp(line, "SET:CHG:", 8) == 0) {
      const char *arg = line + 8;
      if (strcmp(arg, "AUTO") == 0) {
          UL_Charge_Start();
      } else if (strcmp(arg, "STOP") == 0) {
          UL_Charge_Stop();
      } else if (strcmp(arg, "CLEAR") == 0) {
          UL_Charge_ClearFault();
      } else {
          uint32_t v = (uint32_t)strtoul(arg, NULL, 10);
          if (v) {
              UL_ChargeSwitch(1);
          } else {
              UL_Charge_Stop();
          }
      }
  } else if (strncmp(line, "GET:REG", 7) == 0) {
      char rsp[80];
      int n = snprintf(rsp, sizeof(rsp),
                        "$REG,BDTR:%08lX,CCER:%08lX,CR1:%08lX\r\n",
                        (unsigned long)UL_SVPWM_ReadBDTR(),
                        (unsigned long)UL_SVPWM_ReadCCER(),
                        (unsigned long)UL_SVPWM_ReadCR1());
      CDC_Transmit_FS((uint8_t *)rsp, (uint16_t)n);
  }

  USBD_CDC_SetRxBuffer(&hUsbDeviceFS, &Buf[0]);
  USBD_CDC_ReceivePacket(&hUsbDeviceFS);
  return (USBD_OK);
  /* USER CODE END 6 */
}

/**
  * @brief  CDC_Transmit_FS
  *         Data to send over USB IN endpoint are sent over CDC interface
  *         through this function.
  *         @note
  *
  *
  * @param  Buf: Buffer of data to be sent
  * @param  Len: Number of data to be sent (in bytes)
  * @retval USBD_OK if all operations are OK else USBD_FAIL or USBD_BUSY
  */
uint8_t CDC_Transmit_FS(uint8_t* Buf, uint16_t Len)
{
  uint8_t result = USBD_OK;
  /* USER CODE BEGIN 7 */
  uint32_t primask = __get_PRIMASK();
  __disable_irq();
  USBD_CDC_HandleTypeDef *hcdc = (USBD_CDC_HandleTypeDef*)hUsbDeviceFS.pClassData;
  if (hcdc == NULL || hcdc->TxState != 0){
    __set_PRIMASK(primask);
    return USBD_BUSY;
  }
  USBD_CDC_SetTxBuffer(&hUsbDeviceFS, Buf, Len);
  result = USBD_CDC_TransmitPacket(&hUsbDeviceFS);
  __set_PRIMASK(primask);
  /* USER CODE END 7 */
  return result;
}

/**
  * @brief  CDC_TransmitCplt_FS
  *         Data transmitted callback
  *
  *         @note
  *         This function is IN transfer complete callback used to inform user that
  *         the submitted Data is successfully sent over USB.
  *
  * @param  Buf: Buffer of data to be received
  * @param  Len: Number of data received (in bytes)
  * @retval Result of the operation: USBD_OK if all operations are OK else USBD_FAIL
  */
static int8_t CDC_TransmitCplt_FS(uint8_t *Buf, uint32_t *Len, uint8_t epnum)
{
  uint8_t result = USBD_OK;
  /* USER CODE BEGIN 13 */
  UNUSED(Buf);
  UNUSED(Len);
  UNUSED(epnum);
  /* USER CODE END 13 */
  return result;
}

/* USER CODE BEGIN PRIVATE_FUNCTIONS_IMPLEMENTATION */

/* USER CODE END PRIVATE_FUNCTIONS_IMPLEMENTATION */

/**
  * @}
  */

/**
  * @}
  */

